apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-backend
  labels:
    app: food-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: food-backend
  template:
    metadata:
      labels:
        app: food-backend
    spec:
      containers:
      - name: food-backend
        image: gcr.io/food-recipe-cloud/food-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: CONNECTION_STRING
          value: "mongodb://34.9.202.173:27017/foodRecipe"
        - name: SECRET_KEY
          value: "KIRTI12345"
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: food-backend-service
spec:
  selector:
    app: food-backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP

